# This is a basic workflow to help you get started with Actions

name: Reminder

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - master
  schedule:
    - cron: '24 2 * * *'  # 北京时间 10:24 AM

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        env:
          EMAIL_KEY: ${{secrets.EMAIL_KEY}}
          WECHAT_KEY: ${{secrets.WECHAT_KEY}}
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests
          python ./reminder.py
      
      # ~~Python 中发邮件似乎被拦截了~~
      # 已定位到问题 无法发出邮件是发件箱 新浪邮箱的锅
      # 改用 腾讯邮箱没问题
#       - name: Send mail
#         uses: dawidd6/action-send-mail@master
#         with:
#           server_address: smtp.qq.com
#           server_port: 465
#           username: zongyc@foxmail.com
#           password: ${{ secrets.EMAIL_KEY }}
#           subject: 【值日通知】
#           body: file://message.txt
#           to: zongeek@sina.com
#           from: GitHub Actions
#           convert_markdown: true
